<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulário com Login e Edição</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            margin: 0;
        }

        .container {
            max-width: 400px;
            width: 100%;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            text-align: center;
            margin-top: 50px;
        }

        input[type="text"], textarea {
            width: 100%;
            padding: 8px;
            margin: 8px 0;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        button {
            padding: 10px;
            width: 100%;
            border: none;
            background-color: #007bff;
            color: white;
            font-size: 16px;
            cursor: pointer;
            border-radius: 4px;
            margin-top: 10px;
        }

        button:hover {
            background-color: #0056b3;
        }

        /* Ícone de Login */
        .login-icon {
            position: fixed;
            top: 20px;
            right: 20px;
            font-size: 24px;
            cursor: pointer;
        }

        /* Pop-up de Login */
        #loginModal {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.5);
            justify-content: center;
            align-items: center;
        }

        #loginForm {
            background: white;
            padding: 20px;
            border-radius: 5px;
            width: 300px;
            text-align: center;
        }

        .hidden {
            display: none;
        }
    </style>
</head>
<body>

<!-- Ícone de Login -->
<div class="login-icon" onclick="abrirLogin()">
    🔒
</div>

<!-- Pop-up de Login -->
<div id="loginModal">
    <div id="loginForm">
        <h2>Acesso Restrito</h2>
        <input type="password" id="password" placeholder="Digite a senha" required>
        <button onclick="login()">Entrar</button>
        <button onclick="fecharLogin()">Cancelar</button>
    </div>
</div>

<!-- Formulário para responder as perguntas -->
<div id="formulario" class="container">
    <h2>Responda o Formulário</h2>
    <input type="text" id="nomeEmpresa" placeholder="Nome da empresa" required>
    <div id="perguntasContainer"></div>
    <button onclick="salvarResposta()">Enviar Resposta</button>
</div>

<!-- Lista de Respostas (apenas visível para quem tiver a senha) -->
<div id="listaRespostas" class="container hidden">
    <h2>Lista de Respostas</h2>
    <ul id="respostas"></ul>
</div>

<!-- Botões de Edição e Logout (apenas visíveis para quem tiver a senha) -->
<div id="editarPerguntas" class="container hidden">
    <button onclick="adicionarPergunta()">Adicionar Pergunta</button>
    <button onclick="salvarAlteracoes()">Salvar Alterações</button>
    <button onclick="logout()">Logout</button>
</div>

<script>
    const senhaCorreta = "1234"; // Substitua pela senha desejada
    const respostasSalvas = [];
    let perguntas = [{ texto: "Como está você?" }]; // Lista inicial com perguntas

    // Funções para abrir e fechar o login
    function abrirLogin() {
        document.getElementById("loginModal").style.display = "flex";
    }

    function fecharLogin() {
        document.getElementById("loginModal").style.display = "none";
    }

    // Função para validar login
    function login() {
        const senha = document.getElementById("password").value;
        if (senha === senhaCorreta) {
            document.getElementById("listaRespostas").classList.remove("hidden");
            document.getElementById("editarPerguntas").classList.remove("hidden");
            fecharLogin();
            renderizarPerguntas(true); // Renderizar perguntas editáveis
            mostrarRespostas();
        } else {
            alert("Senha incorreta. Tente novamente.");
        }
    }

    // Função de logout
    function logout() {
        document.getElementById("listaRespostas").classList.add("hidden");
        document.getElementById("editarPerguntas").classList.add("hidden");
        renderizarPerguntas(false); // Renderizar perguntas como texto não editável
    }

    // Função para renderizar o formulário com as perguntas
    function renderizarPerguntas(editavel) {
        const perguntasContainer = document.getElementById("perguntasContainer");
        perguntasContainer.innerHTML = ""; // Limpa perguntas anteriores

        perguntas.forEach((pergunta, index) => {
            const perguntaElement = document.createElement("div");
            perguntaElement.className = "pergunta";
            if (editavel) {
                // Campo de texto editável para perguntas quando logado
                perguntaElement.innerHTML = `<input type="text" value="${pergunta.texto}" onchange="editarPergunta(${index}, this.value)">`;
            } else {
                // Texto não editável para perguntas
                perguntaElement.innerHTML = `<textarea placeholder="${pergunta.texto}" readonly></textarea>`;
            }
            perguntasContainer.appendChild(perguntaElement);
        });
    }

    // Renderizar as perguntas ao carregar a página
    renderizarPerguntas(false);

    // Função para salvar a resposta no array
    function salvarResposta() {
        const nomeEmpresa = document.getElementById("nomeEmpresa").value;
        if (!nomeEmpresa) {
            alert("Por favor, insira o nome da empresa.");
            return;
        }

        const respostas = Array.from(document.querySelectorAll("#perguntasContainer textarea")).map(textarea => textarea.value);

        if (respostas.some(resposta => !resposta)) {
            alert("Por favor, responda todas as perguntas.");
            return;
        }

        const respostaObj = {
            nomeEmpresa: nomeEmpresa,
            respostas: respostas
        };
        respostasSalvas.push(respostaObj);
        alert("Resposta enviada com sucesso!");

        // Limpar campos após o envio
        document.getElementById("nomeEmpresa").value = "";
        document.querySelectorAll("#perguntasContainer textarea").forEach(textarea => textarea.value = "");
    }

    // Função para exibir respostas salvas
    function mostrarRespostas() {
        const lista = document.getElementById("respostas");
        lista.innerHTML = "";
        respostasSalvas.forEach((resposta, index) => {
            const item = document.createElement("li");
            item.textContent = `${index + 1}. Empresa: ${resposta.nomeEmpresa} - Respostas: ${resposta.respostas.join(", ")}`;
            lista.appendChild(item);
        });
    }

    // Função para adicionar uma nova pergunta
    function adicionarPergunta() {
        perguntas.push({ texto: `Nova pergunta ${perguntas.length + 1}` });
        renderizarPerguntas(true);
    }

    // Função para editar o texto de uma pergunta
    function editarPergunta(index, novoTexto) {
        perguntas[index].texto = novoTexto;
    }

    // Função para salvar alterações nas perguntas
    function salvarAlteracoes() {
        renderizarPerguntas(false); // Atualiza o formulário com perguntas não editáveis para logout
        alert("Alterações salvas com sucesso!");
    }
</script>

</body>
</html>
